### ISSUE TITLE
Scaling / multiplication is unable to apply factors to temperatures

### ISSUE THREAD

**Issue by milgner** [unitsofmeasurement/indriya#424] opened 2024-07-31 11:10 UTC
Scenario: source data is in tenths of degree celsius. Trying to convert it to degrees celsius results in

> java.lang.UnsupportedOperationException: ℃ is non-linear, cannot convert

Example Test (Kotlin): 

_`ReBasedUnitFormat` is just a utility class around `EBNFUnitFormat` which uses a custom `SymbolMap`_

```kotlin
class UnitsSpec : DescribeSpec({
    it("can deal with centidegrees Celsius") {
        val source: MeasureUnit<*> = ReBasedUnitFormat.parse("°C/10") 
        val dest: MeasureUnit<*> = ReBasedUnitFormat.parse("°C")

        source.getConverterToAny(dest).convert(10).shouldBeEqual(1.0)
    }
})
```

It seems like it should be possible to do this? Is there a way to achieve this with units of measurement without resorting to external scale factors?

**Comment by keilw** [comment] 2024-07-31 12:20
Which Kotlin framework are you using here, Physikal?

I have not looked into that for a while, so `MeasureUnit` does not feel familiar.

**Comment by milgner** [comment] 2024-07-31 12:32
> Which Kotlin framework are you using here, Physikal?
> 
> I have not looked into that for a while, but `MeasureUnit` does not feel familiar.

Sorry, I should have mentioned: `MeasureUnit` is just a type alias defined as

```
typealias MeasureUnit<T> = javax.measure.Unit<T>
```

in order to avoid confusion with the Kotlin `Unit` type.

**Comment by keilw** [comment] 2024-07-31 13:29
So you don't use an extra layer or framework?

Since `CELSIUS` uses an `AddConverter` because 0 Degree Celsius are 273.15 Kelvin, that converter is not linear, that seems the problem here.
@andi-huber, @desruisseaux Any thoughts, is everything correct in `ProductUnit.getSystemConverter()` ?

**Comment by thedanielhanke** [comment] 2024-07-31 14:17
out of interest, why is this not linear? 

A function is linear if it can be written in the form `f(x) = mx + b`, where:

- m is the slope (a constant)
- b is the y-intercept (also a constant)

adding 273.15 to a value x can be written as

`f(x) = 1x + 273.15` 

what am i missing?

**Comment by keilw** [comment] 2024-07-31 14:21
See the answer here: https://www.geeksforgeeks.org/what-is-the-relationship-between-celsius-and-kelvin-scale-of-temperature/

**Comment by thedanielhanke** [comment] 2024-07-31 14:28
i see this vor celsius and kelvin, thank you. <3 

however, celsius to fractions of celsius should not apply to this, right?

**Comment by desruisseaux** [comment] 2024-07-31 14:30
I'm not familiar with Indriya implementation, but I think that when deriving units, it is also okay to apply a multiplication factor for units with offset. Even by application of the rule that calculation must be equivalent to a calculation in the system unit, we have:

* T(K) = T(°C) + 273.15 K    _(apparent unit mismatch, but this is °C definition)_
* T(mk) = T(K) × 1000 mk/K
  * = (T(°C) + 273.15 K) × 1000 mk/K
  * = T(°C) × 1000 mk/K + 273150 mK
* T(m°C) = T(°C) × 1000 mk/K + 273150 mK − (273.15 K × 1000 mk/K)
  * = T(°C) × 1000 mk/K

The offsets before and after the multiplication cancel.

**Note:** The definition of "is linear" in the Unit API is at odd with mathematics. An equation of the form "_T_ × _scale_ + _offset_" is still linear. I do not remember why the group decided to call a unit as "non linear" as soon as its conversion to system unit has a non-zero offset, but it still disturb me.

**Comment by desruisseaux** [comment] 2024-07-31 14:56
Yes, when applying additions/subtractions, the result depends on whether the unit is an absolute measurement or an interval. But multiplications are sometime simpler because a cancellation of the offset happens more easily (not always, but in the case of scaling to deci-, milli-, etc., I think it is the case).

**Comment by thedanielhanke** [comment] 2024-08-05 09:44
So is this a bug which should be fixed?

**Comment by keilw** [comment] 2024-09-29 13:01
No, it's not really a bug, see above, but @desruisseaux so how does Seshat handle those operations? 
It is nothing in the API, but even some of the earliest implementations like `AddConverter` in JSR-275 simply returned `false`. Does anyone here for a long time like @dautelle know, how you came to that conclusion?

**Comment by desruisseaux** [comment] 2024-09-29 14:53
Note: to come back again on @thedanielhanke rightful remark:

> out of interest, why is this not linear? A function is linear if it can be written in the form f(x) = mx + b

I think that the Unit API's usage of "is linear" will be a never-ending cause of confusion, as it diverges from all mathematical definitions I'm aware of. Note that the [What is the Relationship Between Celsius and Kelvin Scale of Temperature?](https://www.geeksforgeeks.org/what-is-the-relationship-between-celsius-and-kelvin-scale-of-temperature/) article does not said that the Celsius scale is not linear. It said that it is "not linearly dependent *with absolute zero*". The _"with absolute zero"_ part is a critical addition to "linearly". The Celsius scale *is* linear, but with a non-zero offset. The offset is the _b_ term in above formula.

When the unit API said "linear", what it really means is that the [level of measurement](https://en.wikipedia.org/wiki/Level_of_measurement) is the **ratio scale**. And when the API said "non-linear", it means **interval scale**. Note that the Levels of measurement do not use the "linear" term anywhere, as both the ratio and interval scales imply linear converters. My personal opinion is that the Unit API's usage of the "linear" term is a bug. The `isLinear()` method should have been `isRatioScale()`. We may not be able to fix that easily, but I think we should at least avoid "linear" in our communications when talking about the Celsius scale.

The Seshat implementation returns `false` for a non-zero offset because this is what the `UnitConverter.isLinear()` method contract requires us to do, not because it agrees with that definition. The implementation contains the following comment:

```java
/**
 * Indicates if this converter is linear in JSR-385 sense (not the usual mathematical sense).
 */
```

Seshat accepts operations such as `Units.CELCIUS.divide(100)`, at least on the development branch (I didn't tested the released version). `UnitFormat` indeed throws an exception, but this is a parsing/formatting issue (I will investigate when I will have a chance). However, I'm not completely sure that accepting `Units.CELCIUS.divide(100)` is the correct thing to do. I think that we have an ambiguity. We clarified that a `Quantity` can be an absolute measurement or an interval, but I do not remember that we did such clarification on `Unit` itself. If we want to clarify that, one possible approach may be to complete the `Unit.getConverterTo(Unit)` method with the following:

```java
UnitConverter getConverterTo(Unit<Q> that, Quantity.Scale scale) throws UnconvertibleException;
```

Note: I'm not saying that we should do that, only that it could be one way among others that we may consider. Another possible way could be to add à `Unit.forScale(Quantity.Scale scale)` method, i.e. to allow each `Unit` instance to exist in two flavours: interval and ratio scales (note: we should not do both ways. It should be one or the other, if any).

I also think that `UnitConverter.isLinear()` should be deprecated and replaced by `UnitConverter.getQuantityScale()` returning `Quantity.Scale`.

**Comment by keilw** [comment] 2024-09-29 15:15
@desruisseaux I'm not sure, how many MRs we'll end up doing anytime soon, because replacing a method in UnitConverter on the API level would require at least another one or two for such a drastic change.

Changing the JavaDoc (guess that's what you mean by "contract") could be a little easier, AFAIR there is also no TCK test on such a fine-grained level that would enforce.

For Indriya it works using the `SimpleUnitFormat` while the more old-style `EBNFUnitFormat` offers the strict definition of `CELSIUS: new TransformedUnit(KELVIN, new AddConverter(273.15)), "Celsius", "\u2103")`

**Comment by keilw** [comment] 2024-09-29 18:34
I created a PR #427, please @andi-huber, @desruisseaux or @dautelle if you can review.

**Comment by andi-huber** [comment] 2024-09-30 04:24
What we mean by `isLinear` is that the function is linear AND passes through the origin. Unfortunately there is no name for this category of functions in math, hence `isLinear` is a semantic approximation and I agree this is misleading.

The simplest solution I can think of would be to deprecate and rename the method to `isLinear` to something more semantically accurate like `isLinearWithoutOffset` or `isLinearAndPassesOrigin`.

**Comment by keilw** [comment] 2024-09-30 07:58
@andi-huber Thanks for the input. I closed the PR.
I would not overcomplicate the API with long and sophisticated names, but let's try to improve the JavaDoc, also and especially in the API. 

Coming back to some temperature conversions: `K = 5/9 * (F - 32) + 273.15` is apparently not linear passing the origin.
How about `C = K + 273.15`?

**Comment by andi-huber** [comment] 2024-09-30 08:01
> I would not overcomplicate the API with long and sophisticated names, but let's try to improve the JavaDoc, also and especially in the API.

I agree. And I also did look at the java-doc, which is pretty clear and does not need any update I think.

Anyway, we could improve the wording of exception messages thrown. I'm preparing a PR.

**Comment by andi-huber** [comment] 2024-09-30 08:27
At least we can improve the wording of various exception messages: https://github.com/unitsofmeasurement/indriya/pull/428

**Comment by keilw** [comment] 2024-09-30 08:43
The question remains, why does `ProductUnit.getSystemConverter()` need this kind of check, while `TransformedUnit.getSystemConverter()` doesn't? 
Hence parsing with `SimpleUnitFormat` (which creates a `TransformedUnit` for "°C/10" instead of a `ProductUnit`) instead of `EBNFUnitFormat` or a derivative works for the desired operation.

**Comment by desruisseaux** [comment] 2024-09-30 08:45
> Changing the JavaDoc (guess that's what you mean by "contract") could be a little easier

We cannot really change the Javadoc, at least not in a way that would change the behaviour of that method, as it would be a compatibility break. The best we could do if we want to fix the naming issue would be to deprecate that method.

> From the Wolfram based test code the conversion between FAHRENHEIT and KELVIN: K = 5/9 * (F - 32) + 273.15 is not supposed to be linear

If we replace _"not supposed to be linear"_ by _"supposed to be a conversion of absolute measurements"_, this is a correct interpretation. But _"supposed to be a conversion of intervals"_ would be correct as well, if this is what the user needs. The problem is that the `Unit` API has no way to let users express their intent (contrarily to `Quantity` thanks to its `Scale` enumeration).

**Comment by andi-huber** [comment] 2024-09-30 08:57
> why does ProductUnit.getSystemConverter() need this kind of check, while TransformedUnit.getSystemConverter() doesn't?

I suppose you can compose a multiplication with an addition transformation using `TransformedUnit`, but that composition is no longer a multiplication transformation. Hence the ProductUnit forbids that.

**Comment by keilw** [comment] 2024-09-30 08:58
That's why I asked @andi-huber, if we could not simply ignore it in `ProductUnit`, especially since `TransformedUnit` implementation does not use it the same way getting to the base converter.

**Comment by andi-huber** [comment] 2024-09-30 09:01
Well if by Product in `ProductUnit` we mean multiplication, then no. If we mean composition, then yes, but then why do we have a `ProductUnit` at all?

**Comment by keilw** [comment] 2024-09-30 14:02
For the `RationalConverter` which is somewhat comparable to Seshat's `LinearConverter` (except for the "offset" part which covers AddConverter) always returns true for `isLinear()`,

**Comment by andi-huber** [comment] 2024-09-30 15:12
> as long as we have two or more ways to model something like "°C/10", shouldn't they all behave the same way?

I'm sorry but °C/10 is not well defined. (While K/10 is.) My understanding is that _Indriya_ is a framework, that should warn you about poor choice of unit composition. Otherwise why use it at all.

**Comment by desruisseaux** [comment] 2024-09-30 15:19
As said before, the `Unit` interface is ambiguous. I don't think that this issue can be solved cleanly without an API change.

**Comment by andi-huber** [comment] 2024-09-30 15:22
> As said before, the Unit interface is ambiguous. I don't think that this issue can be solved cleanly without an API change.

I agree.

**Comment by keilw** [comment] 2024-09-30 20:12
> I'm sorry but °C/10 is not well defined. (While K/10 is.) My understanding is that Indriya is a framework, that should warn you about poor choice of unit composition. Otherwise why use it at all.

@andi-huber is right, and using K, K/10 it works without problems.

The reason for the 0 offset is stated here: https://en.wikipedia.org/wiki/Conversion_of_units#Limitations. 

MR2 introduced the new SI prefixes as the biggest change and improvement. MR1 was much smaller compared to that, because the new `Prefix` or `Scale` already got introduced with 2.0 (JSR-385)

Dealing with quantities and units, while in a few realtime cases might be less performant is the "Higher Level" API, while `UnitConverter` and numeric primitives are more of a Lower Level API. 
I am not convinced, the majority of users would benefit from duplicating e.g. the `Scale` into `Unit` or completely removing the notion of linearity. After all it helps the higher level API together with additional information like the scale.
There is of course a discussion for possible new or improved features in the API: https://github.com/unitsofmeasurement/unit-api/discussions, including a thread about `UnitConverter` and the `linearFactor`: https://github.com/unitsofmeasurement/unit-api/discussions/225.

I will close this ticket, as there are at least 3 possible workarounds:
- Use KELVIN
- Use `SimpleUnitFormat` where possible
- A more sophisticated `ReBasedUnitFormat` that not only tweaks/changes the `SymbolMap`, but does more, e.g. return `TransformedUnit` instead of `ProductUnit` where required.

**Closed by keilw** 2024-09-30 20:12 UTC
Labels: analysis

**Comment by keilw** [comment] 2024-10-06 17:36
I offered a 4th workaround in [AbstractUnit](https://github.com/unitsofmeasurement/indriya/blob/master/src/main/java/tech/units/indriya/AbstractUnit.java)

Can be seen in [TemperatureUnitConverterDemo](https://github.com/unitsofmeasurement/uom-demos/blob/main/console/java17/src/main/java/tech/uom/demo/java17/TemperatureUnitConverterDemo.java)

I know, it's a bit odd to store it in the `Unit` when creating the `UnitConverter`, but both Indriya in the `ProductUnit` and Seshat in the internal `ensureRatioScale()` method of its `Unit` implementations check this in a unit implementiation, so it works there to ignore this check whenever the `RELATIVE` scale is used.

I would not add this to the API right now, after all we just had a MR2 release earlier this year, and it might take another year or more till a MR3 (or even a whole new 3.0 JSR) makes sense. The only reason for a whole new API might be significant JDK changes that make great sense for the measurement world. For those who are curious have a look at the latest [Valhalla demo](https://github.com/unitsofmeasurement/uom-demos/tree/main/lang/valhalla). They work and it is possible to implement `Unit` or `Quantity` in a value class, but these value classes by design do not allow an inheritance chain, so the only real use case might be implementations of `Quantity` which is the real value type in our API.

Using Valhalla would still not require an API change, because the value class would only be used on an implementation level. It might require a breaking change that a certain version of Seshat or Indriya using Valhalla needs JDK 25 or 30 (whenever Valhalla would be ready and final) 

If we released a new version of the API or a MR3, then maybe we could use the more established [Scale of measurement](https://en.wikipedia.org/wiki/Level_of_measurement) which at least for the ratio scale Seshat also uses internally.
And offer the `Scale` enum as a top level type, while deprecating the old `Quantity.Scale`.
Offering maybe a wrapper in places like `QuantityFactory` and implementation classes.

Please discuss this idea here in a new thread: https://github.com/unitsofmeasurement/unit-api/discussions.
