### ISSUE TITLE
Arithmetic operations should be done in system units for certain scales

### ISSUE THREAD

**Issue by filipvanlaenen** [unitsofmeasurement/indriya#128] opened 2018-08-06 06:45 UTC
Implementation of https://github.com/unitsofmeasurement/unit-api/issues/95 and https://github.com/unitsofmeasurement/unit-api/issues/131 in Indriya.

Some examples of the expected behavior:

- 0 ⁰C + 0 ⁰C = 273.15 ⁰C
- 0 ⁰C × 0 ⁰C = 74,610.9225 ⁰C²
- 0 ⁰C × 2 = 273.15 ⁰C
- 273.15 ⁰C / 0 ⁰C = 2 one
- 0 ⁰C / 2 = -136.575 ⁰C

Needs unitsofmeasurement/unit-api#95
Also see https://github.com/unitsofmeasurement/unit-api/wiki/Arithmetic-rules-for-Difference-versus-Absolute-quantities

**Comment by desruisseaux** [comment] 2018-08-06 11:53
Actually it does not depends on the level of quantity (Interval versus Ratio). In current state of Unit API, all `Quantity` instances are assumed to have Ratio level, which is why conversion to system unit is _conceptually_ required for all of them (not only temperature), skipping that conversion only when the implementation can determine that the result would be equivalent. Specifying the level of quantity is a separated issue.

This issue is already fixed in Apache SIS implementation of units of measurement without additional burden and without the need to perform any special case for temperature. I will try to copy the code to seshat this week.

**Comment by keilw** [comment] 2018-08-06 12:38
Well then let's park this till we see, how Seshat deals with it. The users do expect the same behavior for a majority of units, so a `1mi+5in` calculation should be in `MILES` until we introduced something like a target unit for that calculation.

**Comment by keilw** [comment] 2018-08-07 08:59
Please note, while scheduled for 2.0 of course, both this ticket and #124 (which is currently considered prio1, but there are other UnitFormat implementations that can deal with it, so there is a workaround and it only occurs with newly introduced labelled units) should either be solved within 2-3 weeks, otherwise we can't have it in EDR1. And the EDR must be published within 9 months, which is reached in September, so no later than the last week of August everything else goes into the Public Review stage (that is another 6 months later, we should aim for end of the year to be ready for the SI reforms in early 2019)

**Comment by filipvanlaenen** [comment] 2018-08-07 09:32
I found out that we probably have to do the arithmetic in BigDecimal (both for correct precision and overflow handling) and with some conversion anyway, and since I'm moving this code into a single class, implementation would be relatively simple. I had it working for multiplication (quantity × quantity), but haven't had time to check it in and create a pull request.

**Comment by keilw** [comment] 2018-08-07 09:37
Are any other PRs or tickets related to this one? Have not tried for a PR, but issues in Waffle can be marked as needs #X or requires #Y, then they are connected in the Waffle Kanban board.

**Comment by desruisseaux** [comment] 2019-01-28 18:53
**Note:** when Wikipedia said that multiplication of an absolute measurement in Celsius is not allowed, my interpretation is that the multiplication is not allowed with the value _as-is_ (in Celsius). There is nothing saying that we are not allowed to convert the quantity in order to carry the operation.

Multiplying a `Quantity` expressed in `CELSIUS` is not forbidden. What is forbidden is doing multiplication **without prior conversion to ratio units** for some scales. The scale is used for determining how to convert to `KELVIN` before the multiplication:

1. If absolute: convert 2°C as 275.15 K, then multiply.
2. If difference: convert 2°C as 2 K, then multiply.

Implementation is free to convert the result back to °C if they wish. My proposal is to keep the result of case 1 above in kelvin for less surprising behavior. Case 2 can be converted back to Celsius with no harm.

**Comment by thodorisbais** [comment] 2019-02-10 18:45
After discussion with @keilw and given the comments above, it looks like this is one of our major stories for the near future.

@filipvanlaenen I see you mentioned that you've already started working on this. Do we have any update?

**Comment by keilw** [comment] 2019-02-10 19:15
@thodorisbais Thanks for offering to help. @filipvanlaenen has assigned this to himself, so if you were able to help him where necessary, it would be great. The 2.0 milestone tickets that are still open are https://github.com/unitsofmeasurement/indriya/milestone/1. While Compound Formatting already works as intended, parsing is to be done. I should be able to do the lion share of the format epic. Beside that "function" is where this ticket resides, there is also something to do in the "documentation" epic, e.g. JavaDoc, but some of it has already been done.

**Comment by magesh678** [comment] 2019-02-26 06:19
@thodorisbais let me know if you need my helping hand in this implementation.

**Comment by magesh678** [comment] 2019-02-26 07:36
Is this typo mistake
    * 0 ⁰C + 0 ⁰C = 273.15 ⁰C
I think it should be 
    * 0 ⁰C + 0 ⁰C = 273.15 ⁰K 

How will we know the target unit to be converted if it is not part of input?
Will this apply to all unit types (where two type conversion possible - eg: Cel ->Far, Mile -> KM, Mtr -> KM)

**Comment by desruisseaux** [comment] 2019-02-26 08:52
It is not a typo. 0°C + 0°C = 275.15 K + 275.15 K = 550.3 K = 275.15 °C (note: there is no "°" in front of Kelvin units). We know this is counter-intuitive.

About what should be the target units: I don't think it needs to be specified. It can be implementation choice, as long as the result is equivalent. For example 550.3 K is equivalent to 275.15°C, so both are acceptable output. But 275.15 K is not equivalent to above measurements, so it is not allowed.

**Comment by thodorisbais** [comment] 2019-03-02 00:55
> @thodorisbais let me know if you need my helping hand in this implementation.

@magesh678 as you can see (in the discussion above and in the assignees' section of the right top of this issue), Filip is the one who's working on it, so, I guess the question regarding any help should be addressed to him. 😃 

That said, @filipvanlaenen , do you need any help here? 😃

**Comment by magesh678** [comment] 2019-03-04 04:20
Thanks @thodorisbais . @filipvanlaenen Do you need any help here?

**Comment by thodorisbais** [comment] 2019-03-11 07:34
Maybe I/it start/s becoming annoying, but given that our PR is soon, I need to ping @filipvanlaenen again for the status of this issue :-) . Any news, Filip?

**Comment by thodorisbais** [comment] 2019-03-19 13:57
@filipvanlaenen any news here?

**Comment by thodorisbais** [comment] 2019-04-02 16:04
Just a few days left until [Apr. 19](https://github.com/unitsofmeasurement/indriya/milestone/1), so, I need to ask again :-) : @filipvanlaenen any news here? How is this going? Do you need any help?

**Comment by keilw** [comment] 2019-05-12 13:03
@thodorisbais We may have to keep this for an Adopt goal but overall the PRD should be ready. As this is an implementation detail that could still be refinded and improved in the RI. 2.0 Final may not be ready before first days of June so any work done on June 1 would still go there.

**Comment by thodorisbais** [comment] 2019-05-12 13:18
Good point, Werner. Do you also believe there is some need to prepare something beforehand with the people that are already interested in contributing to JCP? It looks like we already have a group of 5 after [this](https://twitter.com/utrechtjug/status/1113694006335221760) tweet.

**Comment by keilw** [comment] 2019-05-12 17:33
Study tickets here that are labelled "Help Needed".

**Comment by dstibbe** [comment] 2019-06-02 20:13
Could it be that you are making the problem bigger than it actually is?  

Celcius and Kelvin are a special case, since they are actually the same scale, but with a different point of origin. 

Perhaps you simply shouldn't make the conversion between C and K transparent for addition and subtraction, so
1C + 1C valid
2K - 2K valid
2C + 1K   invalid
1K - 2C   invalid

unless someone explicitly wants to convert.
so :  
 0C +  toC( 2K )  = -271.15 C
 0K +  toK( 2C )  = 275.15 K

This removes a lot of complexity and ambiguity, as well on the application's side as well as the user's side.

For division  and multiplication C and K are interchangeable (because then K and C are always 'relative' )

2X / 1K  = 2 X/K  == 2X/C
2X * 3K  = 6 X.K  == 6X.C

**Comment by keilw** [comment] 2019-06-03 08:59
@unitsofmeasurement/experts, @unitsofmeasurement/contributors What's your opinion on this?

**Comment by desruisseaux** [comment] 2019-06-03 08:59
Hello @dstibbe. The ambiguities actually arise when trying to do "simple" approaches. K and °C are not always relative, even in the context of operations like A*T or A/T (for example in thermodynamic). 1°C + 1°C is valid… but the result is equals to 275.15°C unless at least one measurement is relative.

We have demonstrated in previous discussions that attempt to apply "simple" approaches lead to mathematical inconsistencies. A strong requirement is to be consistent with arithmetic laws. If A, B and C are measurements, then:

* A + A = 2*A
* A + B = B + A
* (A + B) + C = A + (B + C)
* _etc._

The details have been discussed lengthily in other discussions. The outcome is that if there is no information about whether a measurement is relative or absolute, then we did not find any way to avoid violation of above arithmetic laws other than requesting the result to be _as if_ all calculations were done in system units (implementation are free to optimize, as long as the result is equivalent).

**Comment by keilw** [comment] 2019-06-03 09:57
Based on the Scale we do know if it's relative or absolute now, but there were also questions, if e.g. the outcome of `A + B` would be relative if both were absolute?

**Comment by desruisseaux** [comment] 2019-06-03 10:44
Indeed there is a difficulty there. If _A_ and _B_ are both absolute, then on one hand we would expect the result of _A_ + _B_ to be absolute. But on the other hand we could also expect the result of _A_ - _B_ to be relative. So how do we conciliate A + B = A - (-B) ? I think we started a discussion on that a while ago, but I do not remember where exactly…

**Comment by keilw** [comment] 2019-06-03 15:52
I also asked this to SmartHome, maybe if the approach it used so far could be general enough, then we might use it here, otherwise the enum value could be up to individual applications to decide for now.

**Comment by dstibbe** [comment] 2019-06-07 07:34
@desruisseaux that was my point to start with. There is no simple approach (and yes, I was incorrect about multiplication/division), so, how about not searching for a simple approach and avoid making assumptions?  **Just have the user be explicit.** Especially since C and K are the same unit scale,  just with a different base and that is also what makes this problem different than other units of course; usually the unit scale is what changes and the base stays the same, which makes transparent  conversion possible.


Regarding the starting statement of this thread, that 0C + 0C is expected to be 273,15C is a statement I still object to. aU + bU should always be (a+b)U.
If I would invent a Length unit called the Plumbus, and define it to be   -200m , then it should have no affect on the calculation of meters.  It should **not** suddenly be possible for 0m + 0m = 200m to be correct.


You mentioned some previous lengthy discussions, where can I find these?

**Comment by desruisseaux** [comment] 2019-06-07 08:29
Hello @dstibbe. In the context of unit of measurement, zero has a physical meaning: it is the absence of something (mass, energy, heat, etc). There is only one absolute zero on the temperature scale (absence of heat), and this is 0 K. All other zeros (0°C, 0°F) have no physical meaning for _absolute_ measurement (not to be confused with temperature _increment_ in which case they have a meaning - see below).

Measurements using °C or °F are _interval scales_, while measurements using K is a _ratio scale_. The [Level of measurement page on Wikipedia](https://en.wikipedia.org/wiki/Level_of_measurement) provides a discussion on ratio versus interval scale. The key point is that some arithmetic operations make no sense on interval scales like °C; if we want to carry those operations, we have to convert to a ratio scale first.

The 0°C + 0°C = 273.15°C case can be tested using this [temperature calculator](https://rechneronline.de/temperatur/temperature.php). Quoting them (I agree this is not necessarily an authoritative source, but did not found a more explicit one):

> The common belief, that twice 10°C (or °F) equals 20°C (or °F), is wrong. To correctly multiply values, they must be at an ratio scale, which means they must have an absolute zero. Degrees Celsius (centigrade) and degrees Fahrenheit don't have this, so the value must at first be converted into kelvin, then multiplied and then converted back.

Taking you example with meters, I fully agree that aU + bU shall always be equal to (a+b)U. But a Plumbus unit defined with a zero at -200 meters is not a ratio units. If you walk a distance of one Plumbus unit, then continue walking another Plumbus unit, the total distance that you have walked is not 2 Plumbus units. Multiplying Plumbus unit directly by 2 is physically invalid; you have to convert the Plumbus quantity (an interval scale) to a ratio scale such as meters or inches, perform the calculation, then convert back to Plumbus unit.

The previous discussion were on GitHub issues of Unit-API project, but it was very long and hard. We wrote a summary here: https://github.com/unitsofmeasurement/unit-api/wiki/Arithmetic-operations-on-Quantity

**Comment by keilw** [comment] 2019-06-07 09:11
There was also something here earlier in https://github.com/eclipse/smarthome/pull/5697, what should be the concrete action items if any for the Final release?
We are able to distinguish between `RELATIVE` and `ABSOLUTE`, but we may only pinpoint certain units like `CELCIUS` or `KELVIN` but (due to a Java insufficiency with Generics) cannot track if it's `Temperature`, `Length` or something else.

**Comment by desruisseaux** [comment] 2019-06-07 09:31
I'm not sure there is need for action (or maybe I have missed the point). What are the choices on the table?

Regarding above discussion about whether to allow or disallow 1°C + 1 K for example, I have no objection to leave the choice to implementations. My only requirement is that if an implementation chooses to allow those operations, then the result shall be _as if_ all calculations were done in ratio units (taking in account the `RELATIVE` / `ABSOLUTE` nature of the quantity) before to convert the final result in whatever units the implementation wants.

**Comment by keilw** [comment] 2019-06-07 10:26
Well this is the Reference Implementation, so unless we suggest that `Quantity.add()` and other operations shall be overriden by applications with special requirements, it would also have to be solved in this implementation, even if it was just for `CELSIUS` and `KELVIN` (because extensions like FAHRENHEIT) had to be treated differently) We have a few other local "hacks" primarily because both `KILOGRAM` and `GRAM` are present to properly format these units.

**Comment by dstibbe** [comment] 2019-06-10 14:08
@desruisseaux I agree with most of what you wrote, except for a small point:
0C + 0C = 273.15C makes the assumption that both (0C) are absolute values and not interval values.
If someone walked a distance 1 Plumbus (started at 10, ended at 11 Plumbus), and then another distance of 1 Plumbus (started at 11, ended at 12 Plumbus), he has most definitely traveled a distance 2 Plumbus. Because the context clearly indicates we are talking about 'interval's here and thus must treat them as such.
 Now if you would say: what is 10* 3 plumbus, the answer could be either 30 plumbus (10 times the 3 plumbus interval) or -600 plumbus (10 times the location of 3 plumbus on the scale). This is therefore a calculation I think should only be allowed if it is clearly indicated what should be considered at interval scale and what should be at ratio scale.

I like the quote on wikidedia (https://en.wikipedia.org/wiki/Celsius) :
"Because of this dual usage, one must not rely upon the unit name or its symbol to denote that a quantity is a temperature interval; it must be unambiguous through context or explicit statement that the quantity is an interval."

Whatever is chosen, I'd say, if there is a unit with an interval scale **involved**, have the user be **explicit** about how he wants it to be evaluated. e.g.

2<C, interval> + 2<C, interval> = 4 <C, interval>       = 4 <K>
2<C, interval> + 2<K>               = 4 <C,interval>        = 4 <K>
2<C, ratio> + 2 <C, interval>     = 4 <C, ratio>           = 277.15  <K>
2<C, ratio> + 2 <C, ratio>          = 277.15 <C, ratio>  = 550,3  <K>
2 <C,ratio> + 2 <K>                   = 4 <C, ratio>           =  277.15  <K>

2<C,interval> * 2<K>                 =  4 <C, interval>      = 4<K>
2<C,ratio> * 2<K>                      = 277,15 <C,ratio>    = 550,3 <K>

and thus, given U_i is the unit with an interval scale (e.g C),  U the corresponding ratio scaled unit (e.g. K) and b the distance of the origin of U_i from the U scale (e.g. 273,15):

x <U_i, interval>                                 = x <U>
x <U_i, ratio>                                     = b+x <U>

x <U_i, interval> + y <U_i, interval>  = (x+y) <U>               = (x+y) <U_i, interval>    
x <U_i, interval> + y <U>                  = (x+y) <U>               = (x+y) <U_i, interval>   
x <U_i, ratio> + y <U_i, ratio>          = 2b + (x+y) <U>        = b + (x+y) <U_i, ratio>  
x <U_i, ratio> + y <U_i, interval>      = b + (x+y) <U>         = (x+y) <U_i, ratio>        

v* x <U_i, ratio>                                  = (v* (b +x)) <U>       = (v*b + v*x - b) <U_i, ratio>
x <U_i, ratio> * y <U_i, ratio>             = (x+b)(y+b) <U>      = (x+b)(y+b) - b <U_i, ratio>
x <U_i, ratio> * y <U_i, interval>         =  y*(x+b) <U>          =  y*(x+b) - b <U_i, ratio>  
x <U_i, interval> * y <U_i, interval>    =  y*x <U>                 =  y*x <U_i, interval>   
x <U_i, ratio> * y <U>                        =  y*(x+b) <U>           = (y*b + y*x - b) <U_i, ratio>      
x <U_i, interval> * y <U>                    =  y*x <U>                 =  y*x <U_i, interval>   


PS.
Thanks for the discussion and your patience. This has been very educational for me.

**Comment by desruisseaux** [comment] 2019-06-10 14:50
> 0C + 0C = 273.15C makes the assumption that both (0C) are absolute values and not interval values.

True, but if the user did not said explicitly if the values are interval or absolute measurements, we have to make some assumptions. In past debates we did not found an arithmetically consistent assumption other than assuming that all measurements are absolute (thread of past debates contain equations showing inconsistencies of other assumptions).

For making possible to get 0°C + 0°C = 0°C, we need to explicitly specify that at least one measurement is an interval. The equations that you wrote are fine and illustrate well this need: an information about _ratio_ versus _interval_ scale is attached to every measurements. The currently proposed way to provide this information in JSR-363 is the  `ABSOLUTE` versus `RELATIVE` enumeration. But the principle is similar.

**Comment by keilw** [comment] 2019-06-10 14:53
No it's not provided by JSR-363, it is by JSR-385 however ;-)

**Comment by desruisseaux** [comment] 2019-06-10 15:03
Ah, sorry! Thanks for the correction.

**Comment by keilw** [comment] 2019-06-11 14:19
Please have a look at https://github.com/unitsofmeasurement/indriya/blob/master/src/test/java/tech/units/indriya/quantity/AbsoluteVsRelativeTest.java and https://github.com/unitsofmeasurement/indriya/blob/master/src/test/java/tech/units/indriya/quantity/WolframTuturialTemperatureTest.java based on the Wolfram statements about calculating Temperature quantities. Except 2 all others are met already. 

If there are specific operations that need tweaking or extension, I guess an SPI approach similar to addressing https://github.com/unitsofmeasurement/indriya/issues/229 (while an internal to Quantity arithmetics from a numeric precision point here, the `NumberSystem` can also be extended and exchanged via `SystemLoader`) is worth a thought. It may cover the most basic use cases like `CELSIUS` and `KELVIN` out of the box but allow extending it e.g. if further units are introduced by other systems of units.

**Comment by thodorisbais** [comment] 2019-06-11 20:33
I need a better look at this one so that I can express an opinion. Hopefully, that's gonna happen during the weekend. Good discussions, though, people!

**Comment by dstibbe** [comment] 2019-06-12 19:15
@desruisseaux and that was just my point: **don't make assumptions** when dealing with units that are non-ratio-scale (e.g. C).  Let the user be explicit. Assumptions are what made the spacecraft crash in the first place ;-)

@keilw the tests look great. But like my comment to @desruisseaux , would it be an idea to make RELATIVE/ABSOLUTE mandatory for non-ratio-scale units ?

This is my last comment on this subject :P I think I have bothered you guys enough by now. Thanks for the patience.

**Comment by keilw** [comment] 2019-06-12 19:32
@dstibbe `RELATIVE/ABSOLUTE` is already mandatory (unless explicitly set, quantities are ABSOLUTE because it is the most common case), we decided against the "ratio" or other [LevelOfMeasurement](https://en.wikipedia.org/wiki/Level_of_measurement) earlier. It would be a bit of a challenge to introduce it at this stage because the Public Review is practically code-freeze, unless we came across a convincing reason to bring it back. Only then we could have a distinction between `RATIO` and non-ratio, do you think that could help for a more generic solution?

**Comment by desruisseaux** [comment] 2019-06-12 21:38
Talking about Public Review, is there a place where we can comment? More specifically I'm a little bit confused about the `src/etc/modules/` directory (but I guess that this is the topic of another issue than this page).

**Comment by keilw** [comment] 2019-06-12 22:19
There is no such directory in the RI, and for optional smaller modules there is this ticket: https://github.com/unitsofmeasurement/unit-api/issues/42 It is not subject to the main deliverables but if a tiny box with very constrained memory (e.g. Raspberry Pi Zero or similar) needs a tailor-made version of the API they can use these profiles.

**Comment by keilw** [comment] 2019-06-13 14:05
Coming back to the original problem here, @dstibbe thanks a lot for the detailed listing of possible combinations. The most important question is, can `Scale.ABSOLUTE` and `Scale.RELATIVE` work as substitute for what you called `RATIO` and `INTERVAL`? Because any `Quantity` can be created with a scale, so it is of course possible to tell them apart where needed. 
Simply renaming the `Scale` or even adding the other 2 (we discussed it earlier and boiled it down to just those two) into the enum would also work, it was of course an API change but since we have only limited effects of that `Scale` right now, it could still be possible but it must be prior to 2.0 Final stage.

https://en.wikipedia.org/wiki/Conversion_of_units_of_temperature#Comparison_of_temperature_scales contains a good comparison of temperature scales. It does not talk about `RATIO` or `INTERVAL` there but an "absolute Zero" which is partly why we ended up with `ABSOLUTE` (e.g. `RANKINE` and `KELVIN`) vs. `RELATIVE` (all others in most cases)

However taking the last two cases
```
2<C,interval> * 2 = 4 <C, interval> = 4
2<C,ratio> * 2 = 277,15 <C,ratio> = 550,3
``` 
It just does not seem right if you took 
```
2<ft,interval> * 2 = 4 <ft, interval> = 4
2<ft,ratio> * 2 = 0,3048 <ft,ratio> = 0.6096.
``` 
Taking a forced conversion into the system unit (`METRE`) for the lower example, even if you got the mathematically correct value of `0.6096 m` does not make sense because we must not force-convert `ft` into `m` unless a user or their app really wants to do that conversion.

So all we know at the moment at runtime is the `Quantity.Scale` and the distinct `Unit` either `CELSIUS`, `KELVIN` or otherwise.

**Comment by thodorisbais** [comment] 2019-06-13 20:43
Given that 1. the discussions are escalating to a completely different level, and 2. Filip has not provided any update here for a while, it's wise to remove Filip as the assignee of this issue so that we give the chance to anyone else who might be interested in taking this over.

In case Filip comes back with an update, we can always rediscuss it :-) .

**Comment by keilw** [comment] 2019-06-13 20:49
Thanks, the ticket already has "Help needed" and from what I recall Filip expects a new addition to his family, so I guess he could be busy for a good reason right now ;-)

**Comment by dstibbe** [comment] 2019-06-13 22:55
## Previous equations

To start, in my previous set of equations, the `<K>` was not shown, I've fixed it by making it a code block.
So:
```
2<C,interval> * 2 = 4 <C, interval> = 4
2<C,ratio> * 2 = 277,15 <C,ratio> = 550,3
```
was actually:
```
2<C,interval> * 2 = 4 <C, interval> = 4 <K>
2<C,ratio> * 2 = 277,15 <C,ratio> = 550,3 <K>
```

A small difference, but not unimportant. The K unit is very relevant. I have fixed the previous post.

@keilw Regarding your remark about force convert; I absolutely agree with you. The `= 4<K>` in the above was meant to be read as `== 4<K>`.
 It was merely meant to illustrate equality, not conversion.

## Definitions
Let's start with terminology, I noticed that I myself have not been as consistent as I would like to be
(one reason being that I've learned a lot during this conversation).

Units have a:
* **Absolute scale** = a scale that has a 'true' zero-point as origin (there is nothing lower) in a Dimension, (consequently it is always in a ratio scale), e.g. K
* **Relative scale** = a scale that has an arbitrary origin in a Dimension, e.g. C, , these have a translation from an absolute scale, e.g. +273,15
* **Size** = the magnitude of a single unit 

Quantities are 
* **measurement** = the quantity lies on the scale as defined by the unit, e.g. 1C = 274,15 K 
* **difference** = for the degree of difference between two measurements, e.g. 11C - 10C  = 1C = 1K

If one disagrees with these definitions, don't mind correcting me. I could find no proper alternative for the above term 'measurement' 
in the context of this discussion.

## Temperature

Following these definitions, the units for C and K are, in pseudo code:
```
K = AbsoluteUnit( "K" , Temperature)
C = RelativeUnit( "C" , K + 273,15 )
```

providing quantities for K is done as following:
```
myQ = getQuantity( "3", "K")
```

Since K is in absolute scale (AbsoluteUnit), there is no need to indicate the type of quantity.

When providing quantities for C we should **require(!)** the user to provide an indication of the type of Quantity, because it is a RelativeUnit and
the outcome really depends on it:
```
getQuantity( "3", C , MEASUREMENT) - getQuantity( "2", C , MEASUREMENT) === getQuantity( "1", C , DIFFERENCE)   <-- attention: difference
getQuantity( "3", C , MEASUREMENT) - getQuantity( "2", C , DIFFERENCE)  === getQuantity( "1", C , MEASUREMENT)  <-- attention: measurement
getQuantity( "3", C , MEASUREMENT) - getQuantity( "2", K)               === getQuantity( "274,15", K) 
getQuantity( "3", C , MEASUREMENT) + getQuantity( "2", C , MEASUREMENT) === getQuantity( "278,15", C , MEASUREMENT) 
getQuantity( "3", C , MEASUREMENT) + getQuantity( "2", C , DIFFERENCE)    === getQuantity( "5", C , MEASUREMENT) 
getQuantity( "3", C , MEASUREMENT) + getQuantity( "2", K )              === getQuantity( "278,15", K) 
getQuantity( "3", C , DIFFERENCE)  - getQuantity( "2", C , DIFFERENCE)  === getQuantity( "1", C , DIFFERENCE) 
getQuantity( "3", C , DIFFERENCE)  - getQuantity( "2", K )               === getQuantity( "274,15", K)  
getQuantity( "3", C , DIFFERENCE)  + getQuantity( "2", C , DIFFERENCE)  === getQuantity( "5", C , DIFFERENCE) 
getQuantity( "3", C , DIFFERENCE)  + getQuantity( "2", K )               === getQuantity( "278,15", K) 

```
or
```
xM - yM = (a(x) - a(y))  D         
xM - yD = (x - y)        M         
xM - yB = (b(x) - y)     B       
xM + yM = m(b(x) + b(y)) M
xM + yD = (x + y)        M
xM + yB = (b(x) + y)     B
xD - yD = (x-y)          D
xD - yB = (b(x) - y )    B

where 
M: a measurement quantity in specified RelativeUnits (e.g. C)
D: a difference quantity in specified RelativeUnits (e.g. C)
B: base (which has an absolute unit scale) (e.g. K)
m(): function for converting a base quantity to a measured quantity 
b(): function for converting a measured quantity to a base quantity 

Note:  the above only works with the sizes of the both units being the same (e.g. a C is just as big as a K). If they differ, then the difference quantities
should be converted with a function as well (see: Conversion).
```
@keilw
Interesting to see is that when K comes into the equation, the result will be K, and the information regarding DIFFERENCE/MEASUREMENT is lost 
, since K in the equation had none either. When the K quantity does provide that information, it would also influence the quantity type of the outcome.


## Length

Both ft and m are AbsoluteUnit's in the Length dimension. Unlike K and C, they do not differ in origin. However, where K and C are equal 
in size, ft and m are not.

That means that ft and m would not require a quantity type, since they are both AbsoluteUnits: 

```
getQuantity("2" ,ft> * 2 = 4 <ft> === 1.2192 <m>

```
We can use MEASUREMENT/DIFFERENCE, but it is not required.

### Conversion

How to convert between Relative and Absolute units?

Let's take Plumbus once more :) Now let's **redefine the Plumbus** (Plb) to have an origin at -200 m and have a Plb be the size of 13 m

In pseudo
```
Plb = RelativeUnit("Plb", PlbTranslation(-200,m), PlbSize(13,m) )
```

The conversion between Plb and m would be done as following:
```
Measurement:
myMeasurementInPlb = getQuantity( "5", Plb, MEASUREMENT)

myMeasurementInM = myLengthInPlb*PlbSize - PlbTranslation === getQuantity( 5*13-200, m) == getQuantity( -135, m) 


Difference:
myDifferenceInPlb = getQuantity( "5", Plb, DIFFERENCE)

myDifferenceInM = myLengthInPlb*PlbSize === getQuantity( 5*13, m) == getQuantity( 65, m) 
```



### Same unit, different origin

Lets say you want to do some logic with measurements of the height of the water. In the Netherlands this is done relative to the NAP (Amsterdam Ordnance Datum).

How do we handle that? It is actually irrelevant what the actual height of the NAP is, as long as all are measured alongside it.


We can't say `NAP = RelativeUnit( "m" , M + ??? )`, because a) the unit symbol is the same ('m') and b) we have no idea about the offset.

I would propose something along the lines of:
```
NAP = Reference("m")
```

And Length measurement quantities can be given according to the NAP reference:
```
diffUtrechtAmsterdam = getQuantity( "5", m, NAP) - getQuantity( "2", m, NAP) === getQuantity( "3", m, DIFFERENCE)
napUtrecht = getQuantity( "2", m, NAP) + getQuantity( "3", m, DIFFERENCE) === getQuantity( "5", m, NAP)

``` 

But the following would be invalid:
```
getQuantity( "5", m, MEASUREMENT) + getQuantity( "5", m, NAP) 

getQuantity( "5", m, NAP) + getQuantity( "5", m, SOME_OTHER_REFERENCE) 
```
Since we cannot add NAP to a measurement if we do not know the offset. And we can't add NAP to a measurement of some other reference.


----

@keilw	
Anyway... those are my 2 cents (feels more like a whitepaper somehow). 
I think ABSOLUTE/RELATIVE  are fine as they are now (instead of the MEASUREMENT/DIFFERENCE). But I think they would not cover all scenarios described above.
The above would take a shitton of testing to get it right, if at all. So it would not be sensible to implement now.

**Comment by dstibbe** [comment] 2019-06-13 22:57
> Given that 1. the discussions are escalating to a completely different level, ...

Sorry about that :S

**Comment by keilw** [comment] 2019-06-14 08:24
@dstibbe, @thodorisbais No need to be sorry, that is exactly what a Review is for ;-)
Thanks for the constructive input. Adjusting `ABSOLUTE` or `RELATIVE` scales based on above discussions and guidelines should be rather easy.
For other cases we may have to define tests and see, how to apply.

**Comment by thodorisbais** [comment] 2019-06-18 19:41
Hey @mthoolen, [welcome](https://jcp.org/en/jsr/detail?id=385)!
![Screenshot 2019-06-18 at 21 12 52](https://user-images.githubusercontent.com/5684688/59713722-55e95d80-9210-11e9-8757-0c5780b45d3f.png)

First things first, so, just a few words regarding the logistics: 
- serving JSR-385 as a contributor means that basically, you can contribute code to this JSR
- in addition, you have all the freedom to help with the architecture, etc., so, indeed, as @keilw mentioned during our Adopt-a-JSR Day, having joined as a Contributor grants you 100% contribution rights
- you will soon be added in the @unitsofmeasurement/contributors list as well
- should you have any further questions, we're always here

On topic, what is your take on this one (, given that you have already been exposed to it during our Adopt-a-JSR Day)?

**Comment by mthoolen** [comment] 2019-06-20 06:49
Thanks @thodorisbais, lots to read up on!

Looking at @dstibbe 's comment, I agree with what he said. During the Adopt-a-JSR day I worked on this issue and found a fix for adding relative temperatures in anything but Kelvin. It was based on only converting the value of the quantity if the quantity was relative, or a difference as @dstibbe calls it, and if addition is used in converting. I believe only converting for the ratio (or size?) between two units if it is a relative quantity (or difference) and not for the offset in origin would lead to the right numbers at least.

How do we proceed from here? I can offer my fork for a pull request if you'd like, even though I've only changed the behavior for addition at the moment.

**Comment by keilw** [comment] 2019-06-20 19:07
@mthoolen Yes, if you could propose a pull request, that would be great. We could then have others review it (including @dstibbe although I'm not sure if he's a JCP member but making comments here or reviewing a PR is open to everyone, only those who raise the PR or merge it should be JCP members) to get an outcome everyone feels works best.

**Comment by dstibbe** [comment] 2019-06-21 14:21
@keilw I'd be happy to review it. I'd even be happy to make a PR, but I am indeed not yet a JCP member. I did sign the JCP Full Membership Agreement, but it is waiting for review.

**Comment by keilw** [comment] 2019-06-21 17:23
Cool, no problem to review PRs by others in the meantime. As the PMO accepted somebody else's EG membership for JSR 385 quite recently, should your Full membership get approved within a few weeks rather than months, we could still offer you a full EG membership if you want. Helping this rather sophisticated ticket alone justifies that IMO ;-)

**Comment by keilw** [comment] 2019-07-07 20:55
Closing this, created #247 as a follow up for some lose ends.

**Closed by keilw** 2019-07-07 20:55 UTC
Labels: analysis, function, help wanted, prio:2, to do
