### ISSUE TITLE
format() and parse() in SimpleUnitFormat behave differently upon label()

### ISSUE THREAD

**Issue by DrDaleks** [unitsofmeasurement/indriya#124] opened 2018-07-27 14:44 UTC
Consider the following code
```java
    Unit<Force> lbf = Units.NEWTON.multiply(4.4482216152605); // pound-force
    Unit<Area> sqin = USCustomary.INCH.pow(2).asType(Area.class); // square inch
    Unit<Pressure> psi = lbf.divide(sqin).asType(Pressure.class); // pound-force per square inch
    System.out.println("Pounds per square inch: " + psi);
    SimpleUnitFormat.getInstance().label(psi, "psi");
    System.out.println("Pounds per square inch: " + psi);
    System.out.println("Square psi: " + psi.pow(2));

    System.out.println();

    Unit<Pressure> another_psi = Units.NEWTON.multiply(6895).divide(Units.SQUARE_METRE).asType(Pressure.class);
    System.out.println("Pounds per square inch: " + another_psi);
    SimpleUnitFormat.getInstance().label(another_psi, "psi");
    System.out.println("Pounds per square inch: " + another_psi);
    System.out.println("Square psi: " + another_psi.pow(2));
```
which outputs
```
Pounds per square inch: N*4.4482216152605/in²
Pounds per square inch: psi
Square psi: N*4.4482216152605²/in^4

Pounds per square inch: N*6895.0/m²
Pounds per square inch: psi
Square psi: N*6895.0²/m^4
```
Regardless of the usefulness of a square psi (just a random example), wouldn't it make sense to format it as `psi^2` instead of the fully developed form once the label as been defined in the formatter? It seems the simple formatter(s) dive(s) straight into the ProductUnit's components without considering the (basic) case of a powered "labeled" unit (while powered "base" units render fine as you can see). Bug or feature?

**Comment by adufour** [comment] 2018-07-31 09:41
Thx for the insight. Indeed UCUM/EBNF do improve the refactoring+formatting, but I remain quite a bit confused by the lack of easy-ish way to get "psi^2" or "psi²" displayed (other than by force-labeling it unit as such), while:

1. "psi" is known by all formats (read "explicitly labeled" in the case of SimpleUnitFormat).
2. "psi^2" and "psi²" are both nicely parsed by SimpleUnitFormat and EBNFUnitFormat (once "psi" is labeled in the former case)

Am I missing a fundamental reasoning here? Should I be writing my own format for this (arguably straightforward) use case?
One solution I had envisaged here was to modify ProductUnit to cope for the specific case of a self-powered unit (or better off properly extending it, alas the class is marked final).

The reason I focused on this "toy" example is because I work in a field where custom units are frequent (some of them are purely for internal use and would not benefit UCUM in any way). I thus need to evaluate how much freedom (or lack thereof) the current implementations offer to downstream code in order to simplify unit parsing/manipulation by end-users.

**Comment by keilw** [comment] 2018-07-31 09:47
Thx for the update. If you say, Parsing works after labelling `psi`, but formatting doesn't, even in the same type of `UnitFormat`, then I think it's worth to look after that. It would be a mismatch between formatting and parsing. See above demos, we might add something there or even JUnit tests. Due to the non-SI nature it cannot be tested directly in the RI, but fixing or addressing it, would have to happen here.

**Comment by keilw** [comment] 2018-07-31 11:14
I added a few test lines to `CommonFormatDemo`. They show, both the Unicode and ASCII representation of `psi²` can be parsed. However, as expected in this demo `u1 = ebnf.parse("psi^2")` using `EBNFUnitFormat` fails. I would have been surprised by a side-effect between the two formatters. It could be possible, `UCUMFormat` behaves differently and even `EBNFUnitFormat` might do, but unless `PSI` is known by a Unit system it seems quite unlikely. 
So we'll keep this one open to try archive a consistent behavior between `format` and `parse`.

**Comment by adufour** [comment] 2018-07-31 11:39
Hmm, that's an odd one. On my side the parsing you mentioned works, e.g. running just these few lines
```java
    UnitFormat ebnf = EBNFUnitFormat.getInstance();
    System.out.println(ebnf.format(ebnf.parse("psi^2")));
    System.out.println(ebnf.format(ebnf.parse("psi²")));
```
works (and in both cases produces `lb_av²·g_n²/in_i⁴`)
(NB: I depend on systems-ucum 0.9 and systems-quantity 0.9)

**Comment by keilw** [comment] 2018-07-31 11:52
I did not try it in the UCUM demo. Since all relevant UCUM units are added to `EBNFUnitFormat` via its properties, it may work there but it did not work in the simple Common Units environment.

**Comment by keilw** [comment] 2018-07-31 12:10
It does in `UCUMFormatDemo`. I can't say without digging into the code of each why `EBNFUnitFormat` does seem to react to the `label()` method in `SimpleUnitFormat`, but more importantly, both it and `UCUMFormat` (with certain restrictions, the `PRINT` variant does not parse by design) are synchronous in parsing its own output. E.g. `g_n²·lb_av²/in_i⁴` is properly parsed by `EBNFUnitFormat`, too.

Most importantly (I commented out the line for later testing) 
`u1 = SimpleUnitFormat.getInstance().parse("lb²·(m/s²)*9.80665²/c(cm*254.0)^4")` fails with `SimpleUnitFormat`, so it cannot parse its own output unlike the others.

**Comment by adufour** [comment] 2018-07-31 14:35
My apologies for the confusion, but I have the (surely wrong) impression this is getting slightly off-track from the original issue I reported. Here is another try at explaining what (I think) is wrong:

Suppose I use SimpleUnitFormat (for now) to label a given unit. Then:
- If the unit in question is **not** a product unit (i.e. a base, alternate or transformed unit), then its squared version gets correctly formatted as `label²`
- If the unit in question **is** a product unit, then its squared version is **not** formatted as `label²`, but instead the power is applied to the inner elements

To me that's just a consistency issue, regardless of the formatter being used (but more on that in a bit).

This new toy example exemplifies this behaviour a bit better than my original code:
```java
  public static void main(String... args) {
    UnitFormat formatter = SimpleUnitFormat.getInstance();
    System.out.println("== Use case 1: playing with base units ==");
    AlternateUnit<?> aCd = new AlternateUnit<>(Units.CANDELA, "altCD");

    System.out.println("Candela: " + formatter.format(Units.CANDELA));
    System.out.println("Candela times 2: " + formatter.format(Units.CANDELA.multiply(2)));
    System.out.println("Square Candela: " + formatter.format(Units.CANDELA.pow(2)));
    System.out.println("Alt. Candela: " + formatter.format(aCd));
    System.out.println("Square alt. Candela: " + formatter.format(aCd.pow(2)));

    System.out.println("=> The Candela shall now be known as \"CD\"");
    formatter.label(Units.CANDELA, "CD");

    System.out.println("Candela: " + formatter.format(Units.CANDELA));
    System.out.println("Candela times 2: " + formatter.format(Units.CANDELA.multiply(2)));
    System.out.println("Square Candela: " + formatter.format(Units.CANDELA.pow(2)));
    System.out.println("Alt. Candela: " + formatter.format(aCd));
    System.out.println("Square alt. Candela: " + formatter.format(aCd.pow(2)));

    System.out.println();
    System.out.println("== Use case 2: playing with product units ==");
    ProductUnit<?> cdK = new ProductUnit<>(Units.CANDELA.multiply(Units.KELVIN));
    AlternateUnit<?> aCdK = new AlternateUnit<>(cdK, "altCDK");

    System.out.println("Candela-Kelvin: " + formatter.format(cdK));
    System.out.println("Candela-Kelvin times 2: " + formatter.format(cdK.multiply(2)));
    System.out.println("Square Candela-Kelvin: " + formatter.format(cdK.pow(2)));
    System.out.println("Alt. Candela-Kelvin: " + formatter.format(aCdK));
    System.out.println("Square alt. Candela-Kelvin: " + formatter.format(aCdK.pow(2)));

    System.out.println("=> The Candela-Kelvin shall now be known as \"CDK\"");
    formatter.label(cdK, "CDK");

    System.out.println("Candela-Kelvin: " + formatter.format(cdK));
    System.out.println("Candela-Kelvin times 2: " + formatter.format(cdK.multiply(2)));
    System.out.println("Square Candela-Kelvin: " + formatter.format(cdK.pow(2)));
    System.out.println("Alt. Candela-Kelvin: " + formatter.format(aCdK));
    System.out.println("Square alt. Candela-Kelvin: " + formatter.format(aCdK.pow(2)));
  }
```
This produces the following:
```
== Use case 1: playing with base units ==
Candela: cd
Candela times 2: cd*2.0
Square Candela: cd²
Alt. Candela: altCD
Square alt. Candela: altCD²
=> The Candela shall now be known as "CD"
Candela: CD
Candela times 2: CD*2.0
Square Candela: CD²
Alt. Candela: altCD
Square alt. Candela: altCD²

== Use case 2: playing with product units ==
Candela-Kelvin: CD·K
Candela-Kelvin times 2: (CD·K)*2.0
Square Candela-Kelvin: CD²·K²
Alt. Candela-Kelvin: altCDK
Square alt. Candela-Kelvin: altCDK²
=> The Candela-Kelvin shall now be known as "CDK"
Candela-Kelvin: CDK
Candela-Kelvin times 2: CDK*2.0
Square Candela-Kelvin: CD²·K²      // Problem: this should read "CDK²"!
Alt. Candela-Kelvin: altCDK
Square alt. Candela-Kelvin: altCDK²
```
As you may notice, the only issue lies with the product unit formatting, which is inconsistent.

Now interestingly, if I reproduce the same experiment with `EBNFUnitFormat` instead of `SimpleUnitFormat`, it gets weirder:
```
== Use case 1: playing with base units ==
Candela: ca
Candela times 2: ca·2
Square Candela: ca²
Alt. Candela: altCD
Square alt. Candela: altCD²
=> The Candela shall now be known as "CD"
Candela: ca
Candela times 2: ca·2
Square Candela: ca²
Alt. Candela: altCD
Square alt. Candela: altCD²

== Use case 2: playing with product units ==
Candela-Kelvin: ca·K
Candela-Kelvin times 2: ca·K
Square Candela-Kelvin: ca²·K²
Alt. Candela-Kelvin: ca·K           // Problem: shouldn't this read "altCDK"?
Square alt. Candela-Kelvin: ca·K²           // Problem: shouldn't this read "altCDK²"?
=> The Candela-Kelvin shall now be known as "CDK"
Candela-Kelvin: ca·K
Candela-Kelvin times 2: ca·K
Square Candela-Kelvin: ca²·K²
Alt. Candela-Kelvin: ca·K           // Problem: shouldn't this read "altCDK"?
Square alt. Candela-Kelvin: ca·K²           // Problem: shouldn't this read "altCDK²"?

```
Here the labels are actually never taken into account (neither for product nor alternate units).

**Comment by keilw** [comment] 2018-07-31 14:50
Thanks for the clarification. It should help to narrow it down to e.g. to `ProductUnit`, but the issue is, that at least for certain units, `SimpleUnitFormat.format()` produces different results than `parse()` accepts and what seems worse it won't parse its own format output.

**Comment by adufour** [comment] 2018-07-31 21:38
I think I found at least 2 ways to fix the formatting issue. Basically, what happens is `AbstractUnit.pow(int)` internally powers each side of the product instead of the unit as a whole (thus when you reach the formatting call, it's already too late and the formatter can't be blamed for not trying...).
Simply(?) powering the original unit would suffice, which could be done via
```java
new ProductUnit(new Element[]{ new Element(someProductUnit, exponent, 1) });
```
Since that's all private/inaccessible, I found two independent ways to call this line from client code:
- I removed the `final` tag from `AbstractUnit.pow(int)` to override it in `ProductUnit`
- I replaced the implementation of static `ProductUnit.ofPow(int)`, and called that instead

Both options solve the formatting issue quite nicely (but I have no clue on the potential side-effects).
Thoughts? should I PR any of these (or both)? (If so, I'd obviously apply the same fix for roots)

**Comment by keilw** [comment] 2018-07-31 22:46
Yes please propose a PR. While larger portions of code (several hundred or thousand LOC) advise those who change that much to join the JCP at least as Associate Member (contributor) smaller fixes are OK. Of course you're more than welcome to join the JCP if you want. Thanks.

**Comment by keilw** [comment] 2018-08-06 15:59
@adufour Hi, just wanted to ask, if you may have time for a PR yourself, or if someone else might better work on this based on the evidence gathered here?

**Comment by adufour** [comment] 2018-08-06 18:07
I was working on the PR (for the mislabelling part, that is), but then realised that the fix I found actually broke the formatting "before" labelling. In short:

- The current behaviour formats `cdK.pow(2)` as `CD²·K²` (correct) prior to labelling `CD·K` as `CDK`, and `CD²·K²` (incorrect) afterwards
- With my fix(es), `cdK.pow(2)` now formats as `null²` (incorrect) prior to labelling, but `CDK²` (correct) afterwards

Investigating this as we speak

**Comment by keilw** [comment] 2018-08-07 08:38
Great, thanks a lot for the update. While this has P1 at the moment, and ideally SimpleUnitFormat should work before and after labelling it mostly seems to affect new or unknown units, so we would love to have it in the EDR already, which is due before the end of the month (9M before a Renewal Ballot starts, and we should give the JCP PMO at least a few weeks to process the EDR) So no pressure, if necessary, we could schedule it for the next stage (Public Review, that is also approved by the JCP EC, so a more critical milestone)

**Comment by keilw** [comment] 2018-08-10 16:49
Fixed by https://github.com/unitsofmeasurement/indriya/pull/129

**Closed by keilw** 2018-08-10 16:49 UTC
Labels: bug, in progress, prio:1
